# Frontend MVC deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanagement-dep
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bookmanagement
  template:
    metadata: 
      labels:
        app: bookmanagement
    spec:
      containers:
        - name: bookapp
          image: tanzuacrdemo.azurecr.io/bookapp:v1
          imagePullPolicy: Always   
          ports:
            - containerPort: 8090
          command: ["/bin/sh", "-ec", "sleep 1000"]
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Docker2021"
      imagePullSecrets:
        - name: acr-subha
---
# Frontend MVC service
apiVersion: v1
kind: Service
metadata:
  name: bookmanagement-svc
spec:
  ports: 
  - port: 80
    targetPort: 8090
  selector:
    app: bookmanagement
  type: LoadBalancer
